services:
  backend:
    container_name: gemlist-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8104"
    environment:
      jwt_secret: 'peppebrescia'
      # the path of the backend in nginx or other reverse proxies
      ROOT_PATH:
      # the url of the frontend for CORS, where the requests are coming from - may be useless because of docker network
      FRONTEND_URL:
    volumes:
      - /opt/gemlist/backend/:/app/data
